version: '3'
services:

  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: wazoplatform/wazo-auth-tests
    ports:
      - "9497"
    environment:
      TZ: UTC+1
      XIVO_UUID: the-predefined-xivo-uuid
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - "../..:/usr/src/wazo-auth"
      - "./etc/wazo-auth/conf.d/50-default.yml:/etc/wazo-auth/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/wazo-bus/wazo_bus:/opt/venv/lib/python3.7/site-packages/wazo_bus"

  oauth2sync:
    image: oauth2-synchronization-service
    ports:
      - "80"

  postgres:
    image: wazoplatform/wazo-auth-db:local
    ports:
      - "5432"
    command: "-c 'log_min_duration_statement=0'"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  slapd:
    image: bitnami/openldap
    environment:
      BITNAMI_DEBUG: "true"
      LDAP_PORT_NUMBER: 1389
      LDAP_ROOT: dc=wazo-auth,dc=wazo,dc=community
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: wazopassword
      LDAP_CONFIG_ADMIN_ENABLED: "yes"
      LDAP_CONFIG_ADMIN_USERNAME: admin
      LDAP_CONFIG_ADMIN_PASSWORD: configpassword
    ports:
      - "1389"

  smtp:
    image: munkyboy/fakesmtp
    ports:
      - "25"
