version: '3'
services:

  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: wazoplatform/wazo-auth-tests
    ports:
      - "9497"
    environment:
      TZ: UTC+1
      XIVO_UUID: the-predefined-xivo-uuid
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - "../..:/usr/src/wazo-auth"
      - "./etc/wazo-auth/conf.d/50-default.yml:/etc/wazo-auth/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/opt/venv/lib/python3.7/site-packages/xivo_bus"
    command: "wazo-auth"

  oauth2sync:
    image: oauth2-synchronization-service
    ports:
      - "80"

  postgres:
    image: wazoplatform/wazo-auth-db:local
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  slapd:
    image: nickstenning/slapd
    environment:
      LDAP_DOMAIN: wazo-auth.wazo.community
      LDAP_ORGANISATION: acme
      LDAP_ROOTPASS: wazopassword
    ports:
      - "389"

  smtp:
    image: munkyboy/fakesmtp
    ports:
      - "25"
